export type BankQuestionSeed = {
  id: string;
  grade: 1 | 2 | 3 | 4 | 5 | 6;
  subject: "MATEMATIKA" | "BAHASA_INDONESIA" | "IPAS" | "PENDIDIKAN_PANCASILA" | "BAHASA_INGGRIS";
  topic: string;
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: "A" | "B" | "C" | "D";
};

export const QUESTION_BANK_DATA: BankQuestionSeed[] = [
  // ─── Kelas 1 ───────────────────────────────────────────────────────────────
  // Matematika
  {
    id: "bank-g1-mtk-01",
    grade: 1,
    subject: "MATEMATIKA",
    topic: "Bilangan",
    questionText: "Berapa jumlah apel jika ada 3 apel dan ditambah 2 apel?",
    optionA: "4",
    optionB: "5",
    optionC: "6",
    optionD: "7",
    correctOption: "B",
  },
  {
    id: "bank-g1-mtk-02",
    grade: 1,
    subject: "MATEMATIKA",
    topic: "Operasi",
    questionText: "Hasil dari 8 − 3 adalah ...",
    optionA: "4",
    optionB: "5",
    optionC: "6",
    optionD: "7",
    correctOption: "B",
  },
  {
    id: "bank-g1-mtk-03",
    grade: 1,
    subject: "MATEMATIKA",
    topic: "Geometri",
    questionText: "Bangun datar yang memiliki 3 sisi adalah ...",
    optionA: "Persegi",
    optionB: "Lingkaran",
    optionC: "Segitiga",
    optionD: "Persegi panjang",
    correctOption: "C",
  },
  {
    id: "bank-g1-mtk-04",
    grade: 1,
    subject: "MATEMATIKA",
    topic: "Pengukuran",
    questionText: "Manakah bilangan yang lebih besar?",
    optionA: "7",
    optionB: "3",
    optionC: "5",
    optionD: "2",
    correctOption: "A",
  },
  // Bahasa Indonesia
  {
    id: "bank-g1-bind-01",
    grade: 1,
    subject: "BAHASA_INDONESIA",
    topic: "Huruf",
    questionText: "Huruf vokal dalam kata \"ibu\" adalah ...",
    optionA: "i dan b",
    optionB: "i dan u",
    optionC: "b dan u",
    optionD: "hanya b",
    correctOption: "B",
  },
  {
    id: "bank-g1-bind-02",
    grade: 1,
    subject: "BAHASA_INDONESIA",
    topic: "Kata",
    questionText: "Kata yang tepat untuk menyebut hewan yang mengeong adalah ...",
    optionA: "anjing",
    optionB: "kucing",
    optionC: "ayam",
    optionD: "sapi",
    correctOption: "B",
  },
  {
    id: "bank-g1-bind-03",
    grade: 1,
    subject: "BAHASA_INDONESIA",
    topic: "Kalimat",
    questionText: "Kalimat yang benar adalah ...",
    optionA: "Saya pergi sekolah.",
    optionB: "Saya pergi ke sekolah.",
    optionC: "Saya sekolah pergi.",
    optionD: "Pergi saya sekolah.",
    correctOption: "B",
  },
  {
    id: "bank-g1-bind-04",
    grade: 1,
    subject: "BAHASA_INDONESIA",
    topic: "Kata",
    questionText: "Kata \"rumah\" termasuk jenis kata ...",
    optionA: "kata kerja",
    optionB: "kata benda",
    optionC: "kata sifat",
    optionD: "kata seru",
    correctOption: "B",
  },
  // IPAS
  {
    id: "bank-g1-ipas-01",
    grade: 1,
    subject: "IPAS",
    topic: "Tubuh Manusia",
    questionText: "Organ yang digunakan untuk melihat adalah ...",
    optionA: "telinga",
    optionB: "hidung",
    optionC: "mata",
    optionD: "mulut",
    correctOption: "C",
  },
  {
    id: "bank-g1-ipas-02",
    grade: 1,
    subject: "IPAS",
    topic: "Hewan",
    questionText: "Hewan yang biasa dipelihara di rumah dan suka mengeong adalah ...",
    optionA: "kucing",
    optionB: "ular",
    optionC: "harimau",
    optionD: "gajah",
    correctOption: "A",
  },
  {
    id: "bank-g1-ipas-03",
    grade: 1,
    subject: "IPAS",
    topic: "Tumbuhan",
    questionText: "Bagian tumbuhan yang berada di dalam tanah dan menyerap air adalah ...",
    optionA: "daun",
    optionB: "bunga",
    optionC: "akar",
    optionD: "batang",
    correctOption: "C",
  },
  {
    id: "bank-g1-ipas-04",
    grade: 1,
    subject: "IPAS",
    topic: "Tubuh Manusia",
    questionText: "Kita harus mencuci tangan sebelum makan agar ...",
    optionA: "tangan wangi",
    optionB: "tidak sakit perut",
    optionC: "makan lebih cepat",
    optionD: "tidur nyenyak",
    correctOption: "B",
  },
  // Pendidikan Pancasila
  {
    id: "bank-g1-ppkn-01",
    grade: 1,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Sila Pancasila",
    questionText: "Sila pertama Pancasila adalah ...",
    optionA: "Kemanusiaan yang Adil dan Beradab",
    optionB: "Ketuhanan Yang Maha Esa",
    optionC: "Persatuan Indonesia",
    optionD: "Kerakyatan yang Dipimpin oleh Hikmat Kebijaksanaan",
    correctOption: "B",
  },
  {
    id: "bank-g1-ppkn-02",
    grade: 1,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Gotong Royong",
    questionText: "Contoh sikap gotong royong di sekolah adalah ...",
    optionA: "menyapu kelas bersama teman",
    optionB: "bermain sendirian",
    optionC: "membuang sampah sembarangan",
    optionD: "berkelahi dengan teman",
    correctOption: "A",
  },
  {
    id: "bank-g1-ppkn-03",
    grade: 1,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "NKRI",
    questionText: "Warna merah pada bendera Indonesia melambangkan ...",
    optionA: "kesuburan",
    optionB: "keberanian",
    optionC: "kedamaian",
    optionD: "kemakmuran",
    correctOption: "B",
  },
  {
    id: "bank-g1-ppkn-04",
    grade: 1,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Lingkungan",
    questionText: "Sampah plastik sebaiknya dibuang ke ...",
    optionA: "selokan",
    optionB: "tempat sampah",
    optionC: "halaman sekolah",
    optionD: "jalan raya",
    correctOption: "B",
  },
  // Bahasa Inggris
  {
    id: "bank-g1-ing-01",
    grade: 1,
    subject: "BAHASA_INGGRIS",
    topic: "Colors",
    questionText: "What color is the sky on a sunny day?",
    optionA: "Red",
    optionB: "Blue",
    optionC: "Green",
    optionD: "Yellow",
    correctOption: "B",
  },
  {
    id: "bank-g1-ing-02",
    grade: 1,
    subject: "BAHASA_INGGRIS",
    topic: "Numbers",
    questionText: "How do you say \"lima\" in English?",
    optionA: "Three",
    optionB: "Four",
    optionC: "Five",
    optionD: "Six",
    correctOption: "C",
  },
  {
    id: "bank-g1-ing-03",
    grade: 1,
    subject: "BAHASA_INGGRIS",
    topic: "Family",
    questionText: "Your mother's mother is your ...",
    optionA: "sister",
    optionB: "grandmother",
    optionC: "uncle",
    optionD: "brother",
    correctOption: "B",
  },
  {
    id: "bank-g1-ing-04",
    grade: 1,
    subject: "BAHASA_INGGRIS",
    topic: "School",
    questionText: "We write with a ...",
    optionA: "pencil",
    optionB: "spoon",
    optionC: "shoe",
    optionD: "hat",
    correctOption: "A",
  },

  // ─── Kelas 2 ───────────────────────────────────────────────────────────────
  // Matematika
  {
    id: "bank-g2-mtk-01",
    grade: 2,
    subject: "MATEMATIKA",
    topic: "Bilangan",
    questionText: "Angka 47 terdiri dari ... puluhan dan ... satuan.",
    optionA: "4 dan 7",
    optionB: "7 dan 4",
    optionC: "47 dan 0",
    optionD: "0 dan 47",
    correctOption: "A",
  },
  {
    id: "bank-g2-mtk-02",
    grade: 2,
    subject: "MATEMATIKA",
    topic: "Operasi",
    questionText: "Hasil dari 25 + 18 adalah ...",
    optionA: "33",
    optionB: "41",
    optionC: "43",
    optionD: "53",
    correctOption: "C",
  },
  {
    id: "bank-g2-mtk-03",
    grade: 2,
    subject: "MATEMATIKA",
    topic: "Pengukuran",
    questionText: "Jam menunjukkan pukul 3. Jarum pendek berada di angka ...",
    optionA: "3",
    optionB: "6",
    optionC: "9",
    optionD: "12",
    correctOption: "A",
  },
  {
    id: "bank-g2-mtk-04",
    grade: 2,
    subject: "MATEMATIKA",
    topic: "Geometri",
    questionText: "Bangun datar yang keempat sisinya sama panjang dan semua sudutnya siku-siku adalah ...",
    optionA: "segitiga",
    optionB: "lingkaran",
    optionC: "persegi",
    optionD: "trapesium",
    correctOption: "C",
  },
  // Bahasa Indonesia
  {
    id: "bank-g2-bind-01",
    grade: 2,
    subject: "BAHASA_INDONESIA",
    topic: "Kata",
    questionText: "Ejaan yang benar adalah ...",
    optionA: "aktip",
    optionB: "aktif",
    optionC: "aktiv",
    optionD: "aktipp",
    correctOption: "B",
  },
  {
    id: "bank-g2-bind-02",
    grade: 2,
    subject: "BAHASA_INDONESIA",
    topic: "Imbuhan",
    questionText: "Kata \"menulis\" mengandung imbuhan ...",
    optionA: "me-",
    optionB: "ber-",
    optionC: "pe-",
    optionD: "di-",
    correctOption: "A",
  },
  {
    id: "bank-g2-bind-03",
    grade: 2,
    subject: "BAHASA_INDONESIA",
    topic: "Kalimat",
    questionText: "Kalimat tanya yang tepat adalah ...",
    optionA: "Kamu pergi ke mana?",
    optionB: "Kamu pergi ke mana.",
    optionC: "Kamu pergi ke mana!",
    optionD: "Kamu, pergi ke mana",
    correctOption: "A",
  },
  {
    id: "bank-g2-bind-04",
    grade: 2,
    subject: "BAHASA_INDONESIA",
    topic: "Paragraf",
    questionText: "Paragraf yang baik biasanya diawali dengan ...",
    optionA: "kalimat penutup",
    optionB: "kalimat tanya",
    optionC: "kalimat utama",
    optionD: "kalimat seru",
    correctOption: "C",
  },
  // IPAS
  {
    id: "bank-g2-ipas-01",
    grade: 2,
    subject: "IPAS",
    topic: "Tubuh Manusia",
    questionText: "Makanan sehat yang baik untuk sarapan adalah ...",
    optionA: "nasi dan sayur",
    optionB: "permen saja",
    optionC: "minuman bersoda",
    optionD: "keripik setiap hari",
    correctOption: "A",
  },
  {
    id: "bank-g2-ipas-02",
    grade: 2,
    subject: "IPAS",
    topic: "Hewan",
    questionText: "Kucing melahirkan anaknya. Cara berkembangbiak ini disebut ...",
    optionA: "bertelur",
    optionB: "beranak",
    optionC: "bertunas",
    optionD: "bercambah",
    correctOption: "B",
  },
  {
    id: "bank-g2-ipas-03",
    grade: 2,
    subject: "IPAS",
    topic: "Cuaca",
    questionText: "Saat langit mendung dan turun hujan, cuaca yang terjadi adalah ...",
    optionA: "cerah",
    optionB: "berangin kencang",
    optionC: "hujan",
    optionD: "panas terik",
    correctOption: "C",
  },
  {
    id: "bank-g2-ipas-04",
    grade: 2,
    subject: "IPAS",
    topic: "Tumbuhan",
    questionText: "Tumbuhan membutuhkan sinar matahari untuk ...",
    optionA: "berfotosintesis",
    optionB: "berlari",
    optionC: "berenang",
    optionD: "terbang",
    correctOption: "A",
  },
  // Pendidikan Pancasila
  {
    id: "bank-g2-ppkn-01",
    grade: 2,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Sila Pancasila",
    questionText: "Sila kedua Pancasila mengajarkan kita untuk ...",
    optionA: "menghormati Tuhan",
    optionB: "hidup rukun dan toleran",
    optionC: "membela negara",
    optionD: "memilih pemimpin",
    correctOption: "B",
  },
  {
    id: "bank-g2-ppkn-02",
    grade: 2,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Toleransi",
    questionText: "Sikap toleransi berarti ...",
    optionA: "memaksakan pendapat sendiri",
    optionB: "menghormati perbedaan",
    optionC: "menghindari teman baru",
    optionD: "berkelahi saat tidak setuju",
    correctOption: "B",
  },
  {
    id: "bank-g2-ppkn-03",
    grade: 2,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Gotong Royong",
    questionText: "Kerja bakti membersihkan lingkungan sekolah mencerminkan sila ...",
    optionA: "ketiga",
    optionB: "keempat",
    optionC: "kelima",
    optionD: "pertama",
    correctOption: "A",
  },
  {
    id: "bank-g2-ppkn-04",
    grade: 2,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Lingkungan",
    questionText: "Agar lingkungan tetap bersih, kita harus ...",
    optionA: "membakar sampah di halaman",
    optionB: "membuang sampah pada tempatnya",
    optionC: "menumpuk sampah di sudut kelas",
    optionD: "membuang sampah ke sungai",
    correctOption: "B",
  },
  // Bahasa Inggris
  {
    id: "bank-g2-ing-01",
    grade: 2,
    subject: "BAHASA_INGGRIS",
    topic: "Animals",
    questionText: "A dog says \"woof\". What does a cat say?",
    optionA: "Moo",
    optionB: "Meow",
    optionC: "Oink",
    optionD: "Quack",
    correctOption: "B",
  },
  {
    id: "bank-g2-ing-02",
    grade: 2,
    subject: "BAHASA_INGGRIS",
    topic: "School",
    questionText: "We read books in the ...",
    optionA: "library",
    optionB: "kitchen",
    optionC: "bathroom",
    optionD: "garage",
    correctOption: "A",
  },
  {
    id: "bank-g2-ing-03",
    grade: 2,
    subject: "BAHASA_INGGRIS",
    topic: "Numbers",
    questionText: "What number comes after nine?",
    optionA: "Seven",
    optionB: "Eight",
    optionC: "Ten",
    optionD: "Eleven",
    correctOption: "C",
  },
  {
    id: "bank-g2-ing-04",
    grade: 2,
    subject: "BAHASA_INGGRIS",
    topic: "Colors",
    questionText: "The color of grass is usually ...",
    optionA: "green",
    optionB: "purple",
    optionC: "pink",
    optionD: "gray",
    correctOption: "A",
  },

  // ─── Kelas 3 ───────────────────────────────────────────────────────────────
  // Matematika
  {
    id: "bank-g3-mtk-01",
    grade: 3,
    subject: "MATEMATIKA",
    topic: "Operasi",
    questionText: "Hasil dari 6 × 7 adalah ...",
    optionA: "36",
    optionB: "42",
    optionC: "48",
    optionD: "56",
    correctOption: "B",
  },
  {
    id: "bank-g3-mtk-02",
    grade: 3,
    subject: "MATEMATIKA",
    topic: "Pengukuran",
    questionText: "1 meter sama dengan ... centimeter.",
    optionA: "10",
    optionB: "50",
    optionC: "100",
    optionD: "1000",
    correctOption: "C",
  },
  {
    id: "bank-g3-mtk-03",
    grade: 3,
    subject: "MATEMATIKA",
    topic: "Pecahan",
    questionText: "Jika sebuah kue dibagi menjadi 2 bagian sama besar, setiap bagian adalah ...",
    optionA: "1/3",
    optionB: "1/2",
    optionC: "1/4",
    optionD: "2/3",
    correctOption: "B",
  },
  {
    id: "bank-g3-mtk-04",
    grade: 3,
    subject: "MATEMATIKA",
    topic: "Bilangan",
    questionText: "Bilangan genap di antara 14 dan 20 adalah ...",
    optionA: "15",
    optionB: "17",
    optionC: "16",
    optionD: "19",
    correctOption: "C",
  },
  // Bahasa Indonesia
  {
    id: "bank-g3-bind-01",
    grade: 3,
    subject: "BAHASA_INDONESIA",
    topic: "Teks",
    questionText: "Teks yang menceritakan pengalaman pribadi disebut teks ...",
    optionA: "narasi",
    optionB: "prosedur",
    optionC: "laporan",
    optionD: "iklan",
    correctOption: "A",
  },
  {
    id: "bank-g3-bind-02",
    grade: 3,
    subject: "BAHASA_INDONESIA",
    topic: "Kata",
    questionText: "Sinonim dari kata \"besar\" adalah ...",
    optionA: "kecil",
    optionB: "tinggi",
    optionC: "luas",
    optionD: "lebar",
    correctOption: "C",
  },
  {
    id: "bank-g3-bind-03",
    grade: 3,
    subject: "BAHASA_INDONESIA",
    topic: "Paragraf",
    questionText: "Ide pokok biasanya terdapat pada ...",
    optionA: "kalimat penjelas",
    optionB: "kalimat utama",
    optionC: "judul buku",
    optionD: "halaman belakang",
    correctOption: "B",
  },
  {
    id: "bank-g3-bind-04",
    grade: 3,
    subject: "BAHASA_INDONESIA",
    topic: "Imbuhan",
    questionText: "Awalan \"di-\" pada kata \"dibaca\" menunjukkan ...",
    optionA: "pelaku",
    optionB: "tempat",
    optionC: "penghubung",
    optionD: "penanda pasif",
    correctOption: "D",
  },
  // IPAS
  {
    id: "bank-g3-ipas-01",
    grade: 3,
    subject: "IPAS",
    topic: "Energi",
    questionText: "Sumber energi yang berasal dari matahari disebut energi ...",
    optionA: "listrik",
    optionB: "matahari",
    optionC: "nuklir",
    optionD: "geotermal",
    correctOption: "B",
  },
  {
    id: "bank-g3-ipas-02",
    grade: 3,
    subject: "IPAS",
    topic: "Bumi",
    questionText: "Planet tempat kita hidup disebut ...",
    optionA: "Mars",
    optionB: "Bumi",
    optionC: "Jupiter",
    optionD: "Venus",
    correctOption: "B",
  },
  {
    id: "bank-g3-ipas-03",
    grade: 3,
    subject: "IPAS",
    topic: "Cuaca",
    questionText: "Alat untuk mengukur suhu udara disebut ...",
    optionA: "barometer",
    optionB: "termometer",
    optionC: "mikroskop",
    optionD: "teleskop",
    correctOption: "B",
  },
  {
    id: "bank-g3-ipas-04",
    grade: 3,
    subject: "IPAS",
    topic: "Hewan",
    questionText: "Hewan yang bernapas dengan insang adalah ...",
    optionA: "kucing",
    optionB: "burung",
    optionC: "ikan",
    optionD: "kambing",
    correctOption: "C",
  },
  // Pendidikan Pancasila
  {
    id: "bank-g3-ppkn-01",
    grade: 3,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "UUD 1945",
    questionText: "Undang-Undang Dasar Negara Republik Indonesia tahun 1945 disingkat ...",
    optionA: "UUD 1945",
    optionB: "UU 1945",
    optionC: "Pancasila",
    optionD: "GBHN",
    correctOption: "A",
  },
  {
    id: "bank-g3-ppkn-02",
    grade: 3,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "NKRI",
    questionText: "Ibu kota Negara Kesatuan Republik Indonesia adalah ...",
    optionA: "Surabaya",
    optionB: "Bandung",
    optionC: "Jakarta",
    optionD: "Yogyakarta",
    correctOption: "C",
  },
  {
    id: "bank-g3-ppkn-03",
    grade: 3,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Lingkungan",
    questionText: "Menanam pohon di sekitar rumah dapat membantu ...",
    optionA: "menambah polusi",
    optionB: "mengurangi udara segar",
    optionC: "menjaga kelestarian lingkungan",
    optionD: "membuat tanah kering",
    correctOption: "C",
  },
  {
    id: "bank-g3-ppkn-04",
    grade: 3,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Sila Pancasila",
    questionText: "Lambang sila ketiga Pancasila adalah ...",
    optionA: "bintang",
    optionB: "rantai",
    optionC: "pohon beringin",
    optionD: "kepala banteng",
    correctOption: "C",
  },
  // Bahasa Inggris
  {
    id: "bank-g3-ing-01",
    grade: 3,
    subject: "BAHASA_INGGRIS",
    topic: "Simple Grammar",
    questionText: "Choose the correct sentence.",
    optionA: "She are happy.",
    optionB: "She is happy.",
    optionC: "She am happy.",
    optionD: "She be happy.",
    correctOption: "B",
  },
  {
    id: "bank-g3-ing-02",
    grade: 3,
    subject: "BAHASA_INGGRIS",
    topic: "School",
    questionText: "\"This is my book.\" The word \"my\" shows ...",
    optionA: "color",
    optionB: "number",
    optionC: "ownership",
    optionD: "time",
    correctOption: "C",
  },
  {
    id: "bank-g3-ing-03",
    grade: 3,
    subject: "BAHASA_INGGRIS",
    topic: "Family",
    questionText: "Your father's brother is your ...",
    optionA: "cousin",
    optionB: "uncle",
    optionC: "nephew",
    optionD: "aunt",
    correctOption: "B",
  },
  {
    id: "bank-g3-ing-04",
    grade: 3,
    subject: "BAHASA_INGGRIS",
    topic: "Animals",
    questionText: "A cow gives us ...",
    optionA: "milk",
    optionB: "wool",
    optionC: "honey",
    optionD: "silk",
    correctOption: "A",
  },

  // ─── Kelas 4 ───────────────────────────────────────────────────────────────
  // Matematika
  {
    id: "bank-g4-mtk-01",
    grade: 4,
    subject: "MATEMATIKA",
    topic: "Pecahan",
    questionText: "Pecahan yang setara dengan 1/2 adalah ...",
    optionA: "2/4",
    optionB: "1/3",
    optionC: "3/5",
    optionD: "2/3",
    correctOption: "A",
  },
  {
    id: "bank-g4-mtk-02",
    grade: 4,
    subject: "MATEMATIKA",
    topic: "Geometri",
    questionText: "Luas persegi dengan sisi 5 cm adalah ... cm².",
    optionA: "10",
    optionB: "20",
    optionC: "25",
    optionD: "30",
    correctOption: "C",
  },
  {
    id: "bank-g4-mtk-03",
    grade: 4,
    subject: "MATEMATIKA",
    topic: "Bilangan",
    questionText: "Bilangan 0,5 dapat ditulis sebagai pecahan ...",
    optionA: "1/5",
    optionB: "1/2",
    optionC: "2/5",
    optionD: "5/1",
    correctOption: "B",
  },
  {
    id: "bank-g4-mtk-04",
    grade: 4,
    subject: "MATEMATIKA",
    topic: "Operasi",
    questionText: "Hasil dari 48 ÷ 6 adalah ...",
    optionA: "6",
    optionB: "7",
    optionC: "8",
    optionD: "9",
    correctOption: "C",
  },
  // Bahasa Indonesia
  {
    id: "bank-g4-bind-01",
    grade: 4,
    subject: "BAHASA_INDONESIA",
    topic: "Teks",
    questionText: "Teks yang berisi fakta dan data disebut teks ...",
    optionA: "fiksi",
    optionB: "informasi",
    optionC: "puisi",
    optionD: "drama",
    correctOption: "B",
  },
  {
    id: "bank-g4-bind-02",
    grade: 4,
    subject: "BAHASA_INDONESIA",
    topic: "Puisi",
    questionText: "Baris-baris dalam puisi disebut ...",
    optionA: "bait",
    optionB: "paragraf",
    optionC: "bab",
    optionD: "halaman",
    correctOption: "A",
  },
  {
    id: "bank-g4-bind-03",
    grade: 4,
    subject: "BAHASA_INDONESIA",
    topic: "Imbuhan",
    questionText: "Kata \"pemain\" terbentuk dari awalan ...",
    optionA: "me-",
    optionB: "pe-",
    optionC: "ber-",
    optionD: "ke-",
    correctOption: "B",
  },
  {
    id: "bank-g4-bind-04",
    grade: 4,
    subject: "BAHASA_INDONESIA",
    topic: "Kalimat",
    questionText: "Kalimat efektif adalah kalimat yang ...",
    optionA: "panjang dan bertele-tele",
    optionB: "jelas dan mudah dipahami",
    optionC: "penuh kata asing",
    optionD: "tidak ada subjek",
    correctOption: "B",
  },
  // IPAS
  {
    id: "bank-g4-ipas-01",
    grade: 4,
    subject: "IPAS",
    topic: "Ekosistem",
    questionText: "Komponen ekosistem yang membuat makanan sendiri disebut ...",
    optionA: "konsumen",
    optionB: "produsen",
    optionC: "pengurai",
    optionD: "predator",
    correctOption: "B",
  },
  {
    id: "bank-g4-ipas-02",
    grade: 4,
    subject: "IPAS",
    topic: "Ekosistem",
    questionText: "Contoh produsen dalam ekosistem adalah ...",
    optionA: "ular",
    optionB: "jamur",
    optionC: "pohon",
    optionD: "elang",
    correctOption: "C",
  },
  {
    id: "bank-g4-ipas-03",
    grade: 4,
    subject: "IPAS",
    topic: "Energi",
    questionText: "Energi yang dihasilkan dari air terjun disebut energi ...",
    optionA: "angin",
    optionB: "air",
    optionC: "batu bara",
    optionD: "minyak bumi",
    correctOption: "B",
  },
  {
    id: "bank-g4-ipas-04",
    grade: 4,
    subject: "IPAS",
    topic: "Bumi",
    questionText: "Gerakan Bumi mengelilingi Matahari disebut ...",
    optionA: "rotasi",
    optionB: "revolusi",
    optionC: "gempa",
    optionD: "pasang surut",
    correctOption: "B",
  },
  // Pendidikan Pancasila
  {
    id: "bank-g4-ppkn-01",
    grade: 4,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Keragaman Budaya",
    questionText: "Indonesia memiliki banyak suku dan budaya. Sikap yang tepat adalah ...",
    optionA: "membeda-bedakan teman",
    optionB: "menghormati perbedaan budaya",
    optionC: "hanya berteman sebangsa",
    optionD: "menolak budaya lain",
    correctOption: "B",
  },
  {
    id: "bank-g4-ppkn-02",
    grade: 4,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Gotong Royong",
    questionText: "Semboyan \"Bhinneka Tunggal Ika\" berarti ...",
    optionA: "berbeda-beda tetapi tetap satu",
    optionB: "satu suku satu bahasa",
    optionC: "hanya satu agama",
    optionD: "satu pulau satu negara",
    correctOption: "A",
  },
  {
    id: "bank-g4-ppkn-03",
    grade: 4,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "NKRI",
    questionText: "Lagu kebangsaan Indonesia adalah ...",
    optionA: "Indonesia Pusaka",
    optionB: "Indonesia Raya",
    optionC: "Garuda Pancasila",
    optionD: "Maju Tak Gentar",
    correctOption: "B",
  },
  {
    id: "bank-g4-ppkn-04",
    grade: 4,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Lingkungan",
    questionText: "Menghemat penggunaan air termasuk sikap ...",
    optionA: "boros",
    optionB: "pemarah",
    optionC: "peduli lingkungan",
    optionD: "individualis",
    correctOption: "C",
  },
  // Bahasa Inggris
  {
    id: "bank-g4-ing-01",
    grade: 4,
    subject: "BAHASA_INGGRIS",
    topic: "Simple Grammar",
    questionText: "He ___ to school every day.",
    optionA: "go",
    optionB: "goes",
    optionC: "going",
    optionD: "gone",
    correctOption: "B",
  },
  {
    id: "bank-g4-ing-02",
    grade: 4,
    subject: "BAHASA_INGGRIS",
    topic: "School",
    questionText: "A person who teaches students is a ...",
    optionA: "doctor",
    optionB: "teacher",
    optionC: "driver",
    optionD: "farmer",
    correctOption: "B",
  },
  {
    id: "bank-g4-ing-03",
    grade: 4,
    subject: "BAHASA_INGGRIS",
    topic: "Animals",
    questionText: "Which animal can fly?",
    optionA: "Fish",
    optionB: "Snake",
    optionC: "Bird",
    optionD: "Frog",
    correctOption: "C",
  },
  {
    id: "bank-g4-ing-04",
    grade: 4,
    subject: "BAHASA_INGGRIS",
    topic: "Numbers",
    questionText: "Twelve minus five equals ...",
    optionA: "five",
    optionB: "six",
    optionC: "seven",
    optionD: "eight",
    correctOption: "C",
  },

  // ─── Kelas 5 ───────────────────────────────────────────────────────────────
  // Matematika
  {
    id: "bank-g5-mtk-01",
    grade: 5,
    subject: "MATEMATIKA",
    topic: "Pecahan",
    questionText: "Hasil dari 1/4 + 1/4 adalah ...",
    optionA: "1/8",
    optionB: "2/4",
    optionC: "1/2",
    optionD: "2/8",
    correctOption: "C",
  },
  {
    id: "bank-g5-mtk-02",
    grade: 5,
    subject: "MATEMATIKA",
    topic: "Geometri",
    questionText: "Volume kubus dengan rusuk 3 cm adalah ... cm³.",
    optionA: "9",
    optionB: "18",
    optionC: "27",
    optionD: "36",
    correctOption: "C",
  },
  {
    id: "bank-g5-mtk-03",
    grade: 5,
    subject: "MATEMATIKA",
    topic: "Pengukuran",
    questionText: "1 kilometer sama dengan ... meter.",
    optionA: "10",
    optionB: "100",
    optionC: "500",
    optionD: "1000",
    correctOption: "D",
  },
  {
    id: "bank-g5-mtk-04",
    grade: 5,
    subject: "MATEMATIKA",
    topic: "Operasi",
    questionText: "Hasil dari 15 × 12 adalah ...",
    optionA: "150",
    optionB: "160",
    optionC: "170",
    optionD: "180",
    correctOption: "D",
  },
  // Bahasa Indonesia
  {
    id: "bank-g5-bind-01",
    grade: 5,
    subject: "BAHASA_INDONESIA",
    topic: "Teks",
    questionText: "Teks yang menjelaskan cara membuat sesuatu disebut teks ...",
    optionA: "eksplanasi",
    optionB: "prosedur",
    optionC: "anekdot",
    optionD: "pidato",
    correctOption: "B",
  },
  {
    id: "bank-g5-bind-02",
    grade: 5,
    subject: "BAHASA_INDONESIA",
    topic: "Puisi",
    questionText: "Perbandingan langsung dalam puisi disebut ...",
    optionA: "majas personifikasi",
    optionB: "majas metafora",
    optionC: "majas repetisi",
    optionD: "majas hiperbola",
    correctOption: "B",
  },
  {
    id: "bank-g5-bind-03",
    grade: 5,
    subject: "BAHASA_INDONESIA",
    topic: "Kalimat",
    questionText: "Konjungsi \"karena\" berfungsi untuk menunjukkan ...",
    optionA: "waktu",
    optionB: "tempat",
    optionC: "alasan",
    optionD: "tujuan",
    correctOption: "C",
  },
  {
    id: "bank-g5-bind-04",
    grade: 5,
    subject: "BAHASA_INDONESIA",
    topic: "Imbuhan",
    questionText: "Kata \"kebahagiaan\" memiliki akhiran ...",
    optionA: "-an",
    optionB: "-kan",
    optionC: "-i",
    optionD: "-nya",
    correctOption: "A",
  },
  // IPAS
  {
    id: "bank-g5-ipas-01",
    grade: 5,
    subject: "IPAS",
    topic: "Cuaca",
    questionText: "Angin kencang dan hujan deras yang merusak disebut ...",
    optionA: "badai",
    optionB: "kabut",
    optionC: "gerimis",
    optionD: "embun",
    correctOption: "A",
  },
  {
    id: "bank-g5-ipas-02",
    grade: 5,
    subject: "IPAS",
    topic: "Bumi",
    questionText: "Air yang menguap lalu jatuh kembali sebagai hujan merupakan bagian dari ...",
    optionA: "rantai makanan",
    optionB: "daur air",
    optionC: "fotosintesis",
    optionD: "tektonik lempeng",
    correctOption: "B",
  },
  {
    id: "bank-g5-ipas-03",
    grade: 5,
    subject: "IPAS",
    topic: "Energi",
    questionText: "Panel surya mengubah energi matahari menjadi energi ...",
    optionA: "listrik",
    optionB: "panas bumi",
    optionC: "nuklir",
    optionD: "kimia",
    correctOption: "A",
  },
  {
    id: "bank-g5-ipas-04",
    grade: 5,
    subject: "IPAS",
    topic: "Ekosistem",
    questionText: "Jamur yang menguraikan daun mati termasuk peran ...",
    optionA: "produsen",
    optionB: "konsumen",
    optionC: "pengurai",
    optionD: "herbivora",
    correctOption: "C",
  },
  // Pendidikan Pancasila
  {
    id: "bank-g5-ppkn-01",
    grade: 5,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Pancasila",
    questionText: "Pancasila merupakan dasar negara dan ...",
    optionA: "lagu daerah",
    optionB: "ideologi bangsa",
    optionC: "nama provinsi",
    optionD: "mata uang",
    correctOption: "B",
  },
  {
    id: "bank-g5-ppkn-02",
    grade: 5,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "UUD 1945",
    questionText: "Hak setiap warga negara untuk mendapatkan pendidikan tercantum dalam ...",
    optionA: "lagu daerah",
    optionB: "UUD 1945",
    optionC: "nama jalan",
    optionD: "peta wisata",
    correctOption: "B",
  },
  {
    id: "bank-g5-ppkn-03",
    grade: 5,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Toleransi",
    questionText: "Menghormati teman yang berbeda agama merupakan wujud ...",
    optionA: "intoleransi",
    optionB: "toleransi",
    optionC: "kekerasan",
    optionD: "diskriminasi",
    correctOption: "B",
  },
  {
    id: "bank-g5-ppkn-04",
    grade: 5,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Gotong Royong",
    questionText: "Membantu korban bencana alam mencerminkan nilai ...",
    optionA: "egois",
    optionB: "acuh tak acuh",
    optionC: "kepedulian sosial",
    optionD: "individualisme",
    correctOption: "C",
  },
  // Bahasa Inggris
  {
    id: "bank-g5-ing-01",
    grade: 5,
    subject: "BAHASA_INGGRIS",
    topic: "Simple Grammar",
    questionText: "Yesterday, I ___ football in the yard.",
    optionA: "play",
    optionB: "played",
    optionC: "playing",
    optionD: "plays",
    correctOption: "B",
  },
  {
    id: "bank-g5-ing-02",
    grade: 5,
    subject: "BAHASA_INGGRIS",
    topic: "Simple Grammar",
    questionText: "An elephant is ___ than a cat.",
    optionA: "big",
    optionB: "bigger",
    optionC: "biggest",
    optionD: "more big",
    correctOption: "B",
  },
  {
    id: "bank-g5-ing-03",
    grade: 5,
    subject: "BAHASA_INGGRIS",
    topic: "School",
    questionText: "We use a ruler to measure ...",
    optionA: "temperature",
    optionB: "length",
    optionC: "weight of feelings",
    optionD: "sound",
    correctOption: "B",
  },
  {
    id: "bank-g5-ing-04",
    grade: 5,
    subject: "BAHASA_INGGRIS",
    topic: "Family",
    questionText: "Your mother's sister is your ...",
    optionA: "uncle",
    optionB: "aunt",
    optionC: "cousin",
    optionD: "niece",
    correctOption: "B",
  },

  // ─── Kelas 6 ───────────────────────────────────────────────────────────────
  // Matematika
  {
    id: "bank-g6-mtk-01",
    grade: 6,
    subject: "MATEMATIKA",
    topic: "Operasi",
    questionText: "Hasil dari 2 + 3 × 4 adalah ...",
    optionA: "20",
    optionB: "14",
    optionC: "24",
    optionD: "10",
    correctOption: "B",
  },
  {
    id: "bank-g6-mtk-02",
    grade: 6,
    subject: "MATEMATIKA",
    topic: "Pecahan",
    questionText: "25% dari 80 adalah ...",
    optionA: "15",
    optionB: "20",
    optionC: "25",
    optionD: "30",
    correctOption: "B",
  },
  {
    id: "bank-g6-mtk-03",
    grade: 6,
    subject: "MATEMATIKA",
    topic: "Bilangan",
    questionText: "Perbandingan 2 : 3 sama dengan ...",
    optionA: "4 : 5",
    optionB: "4 : 6",
    optionC: "3 : 2",
    optionD: "6 : 8",
    correctOption: "B",
  },
  {
    id: "bank-g6-mtk-04",
    grade: 6,
    subject: "MATEMATIKA",
    topic: "Geometri",
    questionText: "Luas persegi panjang dengan panjang 8 cm dan lebar 5 cm adalah ... cm².",
    optionA: "13",
    optionB: "26",
    optionC: "40",
    optionD: "80",
    correctOption: "C",
  },
  // Bahasa Indonesia
  {
    id: "bank-g6-bind-01",
    grade: 6,
    subject: "BAHASA_INDONESIA",
    topic: "Teks",
    questionText: "Teks yang bertujuan meyakinkan pembaca disebut teks ...",
    optionA: "persuasi",
    optionB: "petunjuk",
    optionC: "label",
    optionD: "undangan",
    correctOption: "A",
  },
  {
    id: "bank-g6-bind-02",
    grade: 6,
    subject: "BAHASA_INDONESIA",
    topic: "Teks",
    questionText: "Laporan hasil pengamatan biasanya memuat bagian ...",
    optionA: "pantun",
    optionB: "kesimpulan",
    optionC: "dialog drama",
    optionD: "lirik lagu",
    correctOption: "B",
  },
  {
    id: "bank-g6-bind-03",
    grade: 6,
    subject: "BAHASA_INDONESIA",
    topic: "Puisi",
    questionText: "Majas yang memberi sifat manusia pada benda mati disebut ...",
    optionA: "personifikasi",
    optionB: "hiperbola",
    optionC: "metonimia",
    optionD: "sinonim",
    correctOption: "A",
  },
  {
    id: "bank-g6-bind-04",
    grade: 6,
    subject: "BAHASA_INDONESIA",
    topic: "Paragraf",
    questionText: "Paragraf deduktif dimulai dengan ...",
    optionA: "kalimat penjelas",
    optionB: "kalimat penutup",
    optionC: "kalimat utama di awal",
    optionD: "kalimat utama di akhir",
    correctOption: "C",
  },
  // IPAS
  {
    id: "bank-g6-ipas-01",
    grade: 6,
    subject: "IPAS",
    topic: "Keragaman Budaya Indonesia",
    questionText: "Rumah adat Minangkabau dari Sumatera Barat disebut ...",
    optionA: "Joglo",
    optionB: "Honai",
    optionC: "Gadang",
    optionD: "Tongkonan",
    correctOption: "C",
  },
  {
    id: "bank-g6-ipas-02",
    grade: 6,
    subject: "IPAS",
    topic: "Bumi",
    questionText: "Lapisan Bumi yang paling luar dan tempat makhluk hidup berada adalah ...",
    optionA: "inti bumi",
    optionB: "mantel",
    optionC: "kerak bumi",
    optionD: "atmosfer",
    correctOption: "C",
  },
  {
    id: "bank-g6-ipas-03",
    grade: 6,
    subject: "IPAS",
    topic: "Bumi",
    questionText: "Getaran kuat di dalam kerak bumi disebut ...",
    optionA: "gunung api",
    optionB: "gempa bumi",
    optionC: "tsunami",
    optionD: "angin topan",
    correctOption: "B",
  },
  {
    id: "bank-g6-ipas-04",
    grade: 6,
    subject: "IPAS",
    topic: "Ekosistem",
    questionText: "Penebangan pohon sembarangan dapat menyebabkan ...",
    optionA: "tanah lebih subur",
    optionB: "udara lebih segar",
    optionC: "banjir dan erosi",
    optionD: "suhu lebih dingin",
    correctOption: "C",
  },
  // Pendidikan Pancasila
  {
    id: "bank-g6-ppkn-01",
    grade: 6,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "NKRI",
    questionText: "Pemilihan kepala daerah oleh rakyat mencerminkan prinsip demokrasi dalam sila ...",
    optionA: "pertama",
    optionB: "kedua",
    optionC: "ketiga",
    optionD: "keempat",
    correctOption: "D",
  },
  {
    id: "bank-g6-ppkn-02",
    grade: 6,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "UUD 1945",
    questionText: "Kewajiban warga negara adalah ...",
    optionA: "menaati peraturan yang berlaku",
    optionB: "membuang sampah sembarangan",
    optionC: "melanggar hukum",
    optionD: "menghindari pajak",
    correctOption: "A",
  },
  {
    id: "bank-g6-ppkn-03",
    grade: 6,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Keragaman Budaya",
    questionText: "Sikap menghargai budaya daerah lain di Indonesia disebut ...",
    optionA: "xenofobia",
    optionB: "pluralisme dan toleransi",
    optionC: "isolasi",
    optionD: "diskriminasi",
    correctOption: "B",
  },
  {
    id: "bank-g6-ppkn-04",
    grade: 6,
    subject: "PENDIDIKAN_PANCASILA",
    topic: "Lingkungan",
    questionText: "Program 3R (Reduce, Reuse, Recycle) bertujuan untuk ...",
    optionA: "menambah sampah",
    optionB: "mengurangi dampak sampah pada lingkungan",
    optionC: "membakar semua sampah",
    optionD: "membuang sampah ke laut",
    correctOption: "B",
  },
  // Bahasa Inggris
  {
    id: "bank-g6-ing-01",
    grade: 6,
    subject: "BAHASA_INGGRIS",
    topic: "Simple Grammar",
    questionText: "They ___ visit the museum tomorrow.",
    optionA: "will",
    optionB: "wills",
    optionC: "willed",
    optionD: "willing",
    correctOption: "A",
  },
  {
    id: "bank-g6-ing-02",
    grade: 6,
    subject: "BAHASA_INGGRIS",
    topic: "Simple Grammar",
    questionText: "___ do you live? — I live in Jakarta.",
    optionA: "What",
    optionB: "Where",
    optionC: "When",
    optionD: "Who",
    correctOption: "B",
  },
  {
    id: "bank-g6-ing-03",
    grade: 6,
    subject: "BAHASA_INGGRIS",
    topic: "School",
    questionText: "The subject that studies numbers and shapes is ...",
    optionA: "Mathematics",
    optionB: "Music",
    optionC: "Physical Education",
    optionD: "Art",
    correctOption: "A",
  },
  {
    id: "bank-g6-ing-04",
    grade: 6,
    subject: "BAHASA_INGGRIS",
    topic: "Animals",
    questionText: "A baby dog is called a ...",
    optionA: "kitten",
    optionB: "calf",
    optionC: "puppy",
    optionD: "chick",
    correctOption: "C",
  },
];